config/routes.rb
Rails.application.routes.draw do
root 'posts#new'
get 'about' => 'pages#about'
resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def about
 @title = 'About Krati Bansal'
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 def index
     
 end
 def new
     
 end
 def show
 @post = Post.find(params[:id])    
 end
 def create
     @post = Post.new(post_params)
     @post.save
     redirect_to @post
 end
 private def post_params
 params.require(:Instance).permit(:Name,:Deployment,:Region,:Release_server) 
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <ul class="nav nav-pills nav-justified">
          <li class="nav-item">
            <a class="nav-link active" href="#">Created</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#">By</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#">Krati</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#">Bansal</a>
          </li>
        </ul>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>

app/views/posts/index.html.erb
<h1>Index</h1>

app/views/posts/new.html.erb
<br/>
<br/>
<h1 style="padding-left: 10px">Add Instance</h1>
<br/><%= form_for :Instance, url: posts_path do |f| %>
<p>
        <span style="padding-left:10px;"><%= f.label :Name, 'Instance Name' %></span>
    <%= f.text_field(:Name, {:class => 'form-control', :placeholder => "Please enter name of the instance here"}) %>
</p>
<p>
        <span style="padding-left:10px;"><%= f.label :Deployment, 'Deployment' %></span>
    <%= f.text_field(:Deployment, {:class => 'form-control', :placeholder => "Please enter the deployment here"})  %>
</p>
<p>
        <span style="padding-left:10px;"><%= f.label :Region, 'Region' %></span>
    <%= f.text_field(:Region, {:class => 'form-control', :placeholder => "Please enter the region of the instance here"})  %>
</p>
<p>
        <span style="padding-left:10px;"><%= f.label :Release_server, 'Release Server' %></span>
    <%= f.text_field(:Release_server, {:class => 'form-control', :placeholder => "Please enter the release server name here"})  %>
</p>
<p>
        <span style="padding-left:10px;"><%= f.submit %></span>
</p>
<% end %>

app/views/posts/show.html.erb
   <h1><center><br/><br/><br/><br/><br/><br/><br/><i>Your details have been recorded!</i></center></h1> 